### ISSUE TITLE
[Alexis Camarasa]( w3-project_SQL)

### ISSUE THREAD

**Issue by camarasa1987** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#1]
https://github.com/camarasa1987/ALEXISproject_SQL.git

**Comment by OrianAmpuero** [comment]
Muy bien Alexis! En cuanto al código, bien comentado y con conclusiones de las decisiones tomadas; el repo bien pero puedes mejorar el readme y la organización de las carpetas ya que tienes los csv sucios (antiguos) que para eso sirve el .gitignore y separa los archivos para que se vea todo más claro; mira las extensiones del ERD ya que no lo pude abrir desde github. Sigue así que vas bien y animo para el próximo proyecto💪

**Comment by camarasa1987** [comment]
Gracias por el feedback 🙂

Adjunto una captura de pantalla del ERD.

Saludos!

________________________________
