### ISSUE TITLE
[Juan Gouveia](w3-project_SQL)

### ISSUE THREAD

**Issue by JuanGouveia** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#10]
https://github.com/JuanGouveia/SQL-Project.git

**Comment by CharlyKill7** [comment]
Buen proyecto, Juan.

El repo está bien, aunque procura mejorar la distribución en carpetas.  Tienes varios archivos en la carpeta principal, y queda más limpio si lo incluyes en your_code o un src. La limpieza está bien hecha y las querys son correctas, aunque creo recordar que eran diez. Tampoco hubiera estado mal poder visualizar facilmente el EERD. 

No obstante, se nota que entiendes bien SQL, y ese es el objetivo principal de la semana y del proyecto. Sin embargo, te invito a que intentes no mirar mi repo en el futuro. Entiendo que el código no es de nadie, y todo son copias de copias, pero a la hora de aprender, vale más pegarse hasta lograrlo, de un modo u otro.

Asimismo, también te recomiendo generar el texto de tu readme con tus propias palabras. En este caso, inspirarte en el mío te ha valido pero, en el futuro, tendrás que redactar tus propios readme para proyectos que no tendrán un ejemplo previo, así que viene bien hacer el esfuerzo de sacarlo de dentro, para practicar. Además creo que tienes una buena redacción, y no necesitas mirar la de nadie. Simplemente intenta recordar el proceso que seguiste y plasmarlo de forma que se entienda, lo cual te ayudará a su vez a entender todavía mejor lo que has hecho.

En todo caso, el proyecto es bueno y tu entendimiento correcto. Si te digo que no hace falta que mires otros es porque creo que tienes la capacidad para hacer un proyecto propio brillante. Inténtalo la próxima vez.

¡Ánimo!
