### ISSUE TITLE
[Nerea Riveiro](w3-project_SQL)

### ISSUE THREAD

**Issue by NereaRiveiro** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#11]
[Videoclub-Desenganho](https://github.com/NereaRiveiro/Videoclub-Desenganho)

**Comment by CharlyKill7** [comment]
Buen proyecto, Nerea.

El repo está muy bien, en general. Lo organizas todo en carpetas y, además, muestras la estructura del repo en el readme para que el visitante sepa dónde buscar cada cosa. No obstante, me habría gustado que la carpeta 'SQL' la sacaras de 'notebooks', ya que no contiene ninguno. En cuanto al readme, muy bien. Usaste la estructura HTML del mío y, aunque se parecen, la redacción es tan correcta como tuya y la nueva estructura está bien adaptada a tu proyecto. 

Y de hecho, en cuanto al proyecto en sí, qué te puedo decir. Aunque la decisión de cómo hacer la base de datos es muy personal, llegaste a conclusiones muy parecidas a las mías, por las que no puedo estar más de acuerdo. La limpieza también es correcta, y tanto la creación como las querys de SQL están muy bien. Se nota que lo entiendes bastante bien.

En general, es buen proyecto, Nerea, pero me pregunto qué habrías hecho de no haberte inspirado en nada ni nadie. Creo sinceramente que habrías llegado a conclusiones parecidas y, por ello, te animo a intentarlo la próxima vez; seguro que sale algo muy bueno. ¡Estoy deseando verlo!
