### ISSUE TITLE
[LORENZO IMIZCOZ](w3-project_SQL)

### ISSUE THREAD

**Issue by Lorensou** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#12]
https://github.com/Lorensou/w3-project_SQL.git

**Comment by CharlyKill7** [comment]
Buen proyecto, Lorenzo. Algunos comentarios:

- Intenta guardar los archivos del repo en carpetas, por ejemplo: una llamada 'src', con los archivos de código, otra llamada 'img' con las imágenes, etc, como has hecho con los .csv y la carpeta 'data'. 
- El readme es muy mejorable. Se trata de hacer una sinopsis del proyecto, para que quien visite tu repo se haga una idea de lo que va a encontrar en las carpetas. Te invito a consultar otros readme de este mismo proyecto para inspirarte en el futuro. Puedes copiar la estructura html de alguno que te guste (haciendo click en 'raw') y llenarlo con tu propio contenido.
- Intenta la próxima vez hacer el EERD e incluirlo, con el fin de facilitar al lector una guía visual de la nueva estructura que has decidido crear.
- Aunque el nivel de querys no debe ser muy complejo, intenta, si tienes tiempo, tirar alguna más enrevesada que las que tienes en este proyecto. SELECT * está bien, pero prueba a seleccionar sólo algunas columnas. 
- Intenta comentar mejor tu código para que cualquiera pueda entender facilmente lo que haces. 

En definitiva, un proyecto correcto, Lorenzo, pero intenta poner más dedicación a cómo presentas tu repositorio. Al final serán los reclutadores los que vayan a mirarlo y esos detalles pueden resultar decisivos para tu contratación. Ánimo!
