### ISSUE TITLE
[Carlos Clemente](SQL_PROJECT)

### ISSUE THREAD

**Issue by Carlosclementegarcia** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#14]
https://github.com/Carlosclementegarcia/PROYECTO-SHARKS-CARLOS

**Comment by OrianAmpuero** [comment]
Bien Carlos! Pendiente que me hiciste issue de tu proyecto Shark (fíjate en el link de arriba). 
En cuanto al repo está mejor, ya luego podemos ir viendo más tips para mejorarlo visualmente. El código esta bien, los comentarios y todo el proceso del proyecto. Sigue así porque se está notando todo el curro y el avance que llevas estas tres semanas y lo que queda. Animo y a tope! 💪👏
