### ISSUE TITLE
[David Aparicio] ( w3-project_SQL)

### ISSUE THREAD

**Issue by dapafer** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#16]
https://github.com/dapafer/sql-data-base-building

**Comment by OrianAmpuero** [comment]
Muy buen trabajo David!! En cuanto al código, el ERD y el repo. Trata de usar el .gitignore para guardar los csv sucios y así no tener todo arriba. Sigue así que vas bien💪
