### ISSUE TITLE
[Augusto Abad Varela](2_IRONHACK_MySQL)

### ISSUE THREAD

**Issue by gusavato** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#17]
https://github.com/gusavato/2_IRONHACK_MySQL

**Comment by OrianAmpuero** [comment]
Tremendo trabajo Gus!! Muy bien hecho, súper completo y la verdad no tenga pegas👏 Se nota el curro detrás de todo y el conocimiento puesto en práctica. Solo decirte que sigas así y estás haciendo tu portfolio muy bien🚀
