### ISSUE TITLE
[Anton Utray](w3-project_SQL)

### ISSUE THREAD

**Issue by Anton-Utray** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#18]
https://github.com/Anton-Utray/SQL_DataBase

**Comment by OrianAmpuero** [comment]
Bravooo👏 
Muy bien hecho Anton!! En cuanto al repo todo correcto y el código bien con sus comentarios, funciones, bien usado el .gitignore y ya solo te faltó presentar.
