### ISSUE TITLE
[Javier R.](w3-project_SQL)

### ISSUE THREAD

**Issue by jrodrisanz** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#19]
https://github.com/jrodrisanz/ProyectoSQL

**Comment by CharlyKill7** [comment]
Buen proyecto, Javi. 

El repo está muy bien, con un readme correcto y una buena estructura de carpetas. Se nota que has trabajado y te has sumergido en SQL, que es de lo que se trataba. Sólo un par de comentarios:

- En el archivo de querys.ipynb solamente hay una query. En el readme me muestras las tablas que te salen pero me hubiera gustado poder consultar tu código. Ténlo en cuenta para la próxima vez.
- Veo por tu EERD que has unido inventario con alquiler, siendo inventory_id la PK en inventario y la FK en alquiler. Es muy posible que eso te haya roto las relaciones de las tablas, así que te animo a comprobarlo haciendo un reverse y a intentar descubrir e interiorizar el porqué. 

Esta semana has estado malo y, sin embargo, no se nota en tu proyecto. Sigue así!
