### ISSUE TITLE
[Luis Galdeano](w3-project_SQL)

### ISSUE THREAD

**Issue by LuisGaldeano** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#20]
https://github.com/LuisGaldeano/ProyectoSQL

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Luis.

Para empezar, el repositorio está bien estructurado, con todo en sus carpetas correspondientes e, incluso, con un readme que te lleva directamente al archivo que corresponde a la etapa mencionada. Te felicito por ello. Sin embargo, déjame decirte que la etapa 1, "crear el repo del proyecto", no es necesaria que la reflejes en el readme. Entiendo que desde un punto de vista académico está bien, pero tenéis que empezar a pensar en vuestros repos como proyectos propios que serán visitados por gente que nada tiene que ver con el curso. Además, intenta que la primera frase del readme sea más explicativa respecto a lo qu había que hacer: crear una base de datos.

En cuanto al proyecto en sí, en genral está bien. La limpieza es correcta y la construcción de la base de datos, efectiva. La decisión de cómo plantear el nuevo negocio es muy personal, pero echo de menos una conexión entre rental (que no deja de ser un registro de los alquileres) y el inventario, para que cuando el videoclub vuelva a echar a andar puedan registrarse automaticamente los cambios de inventario en función de qué peliculas se lleven los clientes.

Sigue así, Luis, que vas genial!
