### ISSUE TITLE
[joe sebastian](w3-project_SQL)

### ISSUE THREAD

**Issue by joeSL-ms** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#21]

**Comment by CharlyKill7** [comment]
Buen proyecto, Joe. Permíteme algunos comentarios:

- Acuérdate de copiar el enlace a tu repo de proyecto en la issue que abres en el repo de proyecto de Ironhack.
- Tienes un read.me en el repo, además de tu readme.md. Asegúrate de borrar lo que no sirva, que nuestros repos serán vistos pos reclutadores y esos detalles pueden marcar la diferencia. . También es bueno que organices el repo en carpetas, que pongas nombres explicativos a los archivos, etc.
- En el mismo sentido, intenta cuidar la escritura en el readme, al menos poniendo las mayúsculas y los signos de puntuación que convengan. Es tan importante lo que quieres decir como cómo lo dices, porque lo segundo influye en el receptor de tu mensaje hasta el punto de condicionar lo primero.  Tal vez aquí me esté extralimitando, pero sé que tienes buenas ideas y precisamente por eso lo digo, porque es una lástima que se puedan quedar por el camino por no expresarlas de mejor modo.
- Veo por tu EERD que has unido inventory con renta, siendo inventory_id la PK en inventory y la FK en rental. Es muy posible que eso te haya roto las relaciones de las tablas, así que te animo a comprobarlo haciendo un reverse y a intentar descubrir el porqué.

El resto está bien, las querys son correctas y la limpieza también. Era un proyecto muy personal en ese sentido, y lo importante era la pelea con SQL. Creo que has entendido lo que hay que entender, así que enhorabuena. Intenta mejorar las cositas que faltan, que las cosas que tienes ya las tienes y son muchas. Ánimo!
