### ISSUE TITLE
[Jesus Guardia Ramirez] (w3-project_SQL)

### ISSUE THREAD

**Issue by JesusGuardiaRamirez** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#23]
Completed. Sorry about the wait.
J.

**Comment by CharlyKill7** [comment]
Proyecto correcto, David. Permíteme algún comentario:

- El repo está bien, con una buena organización en carpetas y un readme correcto, aunque te sugiero ocultar los viejos csv sucios usando el .gitignore.
- La primera query, la de las películas más alquiladas, no parece estar bien hecha. No usas el rental_id que has puesto de FK en film_old_hdd, y sin usar ese id es complicado que saques el nº de veces que se alquila una peli. 
- Algunas de las consideraciones que haces en tu readme podrían no ser correctas, como por ejemplo que "Una película puede tener muchas copias, pero una copia sólo puede estar en una tienda". Te invito a, si tienes tiempo, revisar las tablas originales y tratar de entender mejor cómo se relacionan tanto las columnas que contienen como las propias tablas entre sí.

En todo caso, este es un proyecto de ingeniería y no se trata de hacerlo perfecto. Creo que has entendido muchas cosas de SQL, tanto de su lenguaje como su estructura, pasando incluso por instalación/desinstalación de Workbench y de servidor. A partir de aquí, ya te toca trabajarlo a ti. Sigue así!
