### ISSUE TITLE
['Daniel Villanueva']['Proyect_SQL']

### ISSUE THREAD

**Issue by DFDA19** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#3]
https://github.com/DFDA19/Proyect_SQL

**Comment by OrianAmpuero** [comment]
Bien Daniel! Va mejorando el repo, pero recuerda poner todos los archivos en carpetas y ponerle más detalle al readme. En cuanto al código, coméntalo más, tu Daniel del futuro lo agradecerá y no dejes los errores printeados que no se ve bien ni el código que no te funciono. Faltó el ERD para ver las tablas y sus relaciones.
Se va notando los avances en cuanto a trabajo y resultados, así que animo!! 👏
