### ISSUE TITLE
[Juan Núñez](Proyecto_SQL)

### ISSUE THREAD

**Issue by pizornpy** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#6]

**Comment by CharlyKill7** [comment]
Un proyecto muy limitado, Juan, supongo que ya lo sabes. 

Entiendo que no consiguieras subir los datos, aunque tenías tres maneras y varios días para intentarlo. Si ni así lo hubieras logrado, siempre puedes echar el resto en lo que sí puedes hacer. Por ejemplo, hacer el EERD y presentar la captura para acompañar una explicacion de cómo has diseñado la base de datos. Al final, tengas los datos insertados o no, podías hacer todo el trabajo colindante y mostrarlo igualmente. Podías hacer el readme correcto y después decirnos en persona lo que no has puesto, porque además así no queda reflejado en tus repositorios, los cuales terminarán visitando los reclutadores.

Te invito a que en próximos proyectos encuentres la forma de demostrar tu trabajo, a pesar de los problemas. Sé que eres capaz de mucho más. ¡Ánimo!
