### ISSUE TITLE
[Carlos Palomares] ( w3-project_SQL)

### ISSUE THREAD

**Issue by CarlosPalomaresGarcia** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#7]
https://github.com/CarlosPalomaresGarcia/Project3IronHack.git

**Comment by OrianAmpuero** [comment]
Muy bien Carlos!! Todo correcto, la limpieza de datos con las queries y el repo. Sigue así porque vale la pena el resultado.

En cuanto a la presentación:
-Mejorar saludo inicial
-Cuidado el lenguaje
-Buen control del tiempo aunque muy poco quizás
