### ISSUE TITLE
[Carolina Rivera](w3-project_SQL)

### ISSUE THREAD

**Issue by carolinariveraa** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#8]
https://github.com/carolinariveraa/SQL-Database.git

**Comment by OrianAmpuero** [comment]
Muy bien Caro!! Excelente trabajo, en cuanto al código, el ERD y el repo. Sigue así💪

En cuanto a la presentación:
-Mejora la saludo
-No mires tanto la pantalla
-Mejorar apoyo visual para tener atento al público (por ejemplo el ERD)
-Bien de tiempo
