### ISSUE TITLE
[Ignacio Romero][w3-project_SQL]

### ISSUE THREAD

**Issue by Linxx333** [Ironhack-Data-Madrid-Abril-2023/w3-project_SQL#9]

**Comment by Linxx333** [comment]
https://github.com/Linxx333/Ironflix-Data-Base

**Comment by Linxx333** [comment]
Muchas gracias por ser comprensivos

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Nacho.

Se nota que has entendido muy bien cómo funciona SQL; así lo refleja tu proyecto. Aunque la decisión de cómo plantear la nueva base de datos es muy personal, hay ciertas pautas objetivas que deben seguirse, restricciones a tener en cuenta, etc. En cómo eliges las tablas que te quedas y, sobre todo, en cómo las relacionas, se percibe claramente que entiendes las implicaciones de lo que decides hacer. Asimismo, la limpieza con pandas es más que correcta. La distribución del repo, con todo en carpetas adecuadas, también. 

Por ponerte algún "pero", acuerdáte de borrar archivos duplicados en tu repo: tienes dos 'Querys.sql'. Por otro lado, ya que tu proyecto es bueno, te invito a que tu readme sea todavía mejor. Por ejemplo, el apartado 'Dato' tal vez no era necesario en este proyecto. También te impito a poner los signos de puntuación que te faltan y a tratar de imaginar lo que ahí pones cómo la contraportada de un libro; debe darte una idea del contenido y servir para engancharte, sin ser tan larga que no dé pereza leerlo. 

En general, el proyecto está muy bien. Simplemente, intenta mejorar la forma porque el fondo está genial. Y aquí no me refiero tanto al proyecto como a todo tu código en general, que ambos sabemos que es funcional pero podría ser más limpio. ¡Sigue así!
